import {AnimationScaleInRight,AnimationScaleInRightDown,AnimationScaleInRightUp,AnimationRotateInLeft,CustomAnimation,BaseLeftToRightGesture} from "./Animation";

export default {
	AnimationScaleInRight:AnimationScaleInRight,
	AnimationScaleInRightDown:AnimationScaleInRightDown,
	AnimationScaleInRightUp:AnimationScaleInRightUp,
	AnimationRotateInLeft:AnimationRotateInLeft,
	CustomAnimation:CustomAnimation,
	BaseLeftToRightGesture:BaseLeftToRightGesture
}